<template>
  <div>
    <div class="typebox">
      <div class="search">
        <img
          src="https://res.wx.qq.com/wxaproducttrade/dist/images/search_4afbde.svg"
          alt=""
          class="search_main_search"
        />
        <input type="text" placeholder="搜索" class="search_main_input" />
      </div>
      <div class="select_cate">
        <template v-for="(item, index) of string">
          <selectbox
            :number="index"
            :active="choose[index]"
            :click_list="click_list"
            :productCats="item"
            :key="index"
          />
        </template>
      </div>
    </div>
  </div>
</template>

<script>
import Selectbox from "./selectbox";
export default {
  name: "SelectList",
  components: { Selectbox },
  data() {
    return {
      choose: [5],
      string: [
        [
          {
            catId: "1001",
            name: "个人护理",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              limit: "9",
              componentCatGroup: 3,
            },
          },
          {
            catId: "1069",
            name: "农资园艺",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1142",
            name: "厨具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1208",
            name: "宠物生活",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1247",
            name: "家具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1421",
            name: "家居日用",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1453",
            name: "家庭清洁/纸品",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1495",
            name: "家用电器",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1653",
            name: "家纺",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1701",
            name: "家装建材",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1941",
            name: "手机通讯",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1972",
            name: "数码",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6033",
            name: "服饰内衣",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6153",
            name: "母婴",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6263",
            name: "汽车",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6472",
            name: "玩具乐器",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6625",
            name: "生鲜",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6706",
            name: "电脑、办公",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6831",
            name: "箱包皮具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6870",
            name: "美妆护肤",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6932",
            name: "运动户外",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7363",
            name: "钟表",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7378",
            name: "鞋靴",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7419",
            name: "食品饮料",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "128209",
            name: "旅游休闲",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "135835",
            name: "图书",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "376707",
            name: "二手",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 2,
            },
          },
          {
            catId: "377078",
            name: "生活服务",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "378136",
            name: "珠宝首饰",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 2147483647,
            },
          },
          {
            catId: "381003",
            name: "教育培训",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 2147483647,
            },
          },
          {
            catId: "429008",
            name: "其他",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
        ],
        [
          {
            catId: "1001",
            name: "个人护理",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              limit: "9",
              componentCatGroup: 3,
            },
          },
          {
            catId: "1069",
            name: "农资园艺",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1142",
            name: "厨具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1208",
            name: "宠物生活",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1247",
            name: "家具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1421",
            name: "家居日用",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1453",
            name: "家庭清洁/纸品",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1495",
            name: "家用电器",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1653",
            name: "家纺",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1701",
            name: "家装建材",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1941",
            name: "手机通讯",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1972",
            name: "数码",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6033",
            name: "服饰内衣",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6153",
            name: "母婴",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6263",
            name: "汽车",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6472",
            name: "玩具乐器",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6625",
            name: "生鲜",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6706",
            name: "电脑、办公",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6831",
            name: "箱包皮具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6870",
            name: "美妆护肤",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6932",
            name: "运动户外",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7363",
            name: "钟表",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7378",
            name: "鞋靴",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7419",
            name: "食品饮料",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "128209",
            name: "旅游休闲",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "135835",
            name: "图书",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "376707",
            name: "二手",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 2,
            },
          },
          {
            catId: "377078",
            name: "生活服务",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "378136",
            name: "珠宝首饰",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 2147483647,
            },
          },
          {
            catId: "381003",
            name: "教育培训",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 2147483647,
            },
          },
          {
            catId: "429008",
            name: "其他",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
        ],
        [
          {
            catId: "1001",
            name: "个人护理",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              limit: "9",
              componentCatGroup: 3,
            },
          },
          {
            catId: "1069",
            name: "农资园艺",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1142",
            name: "厨具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1208",
            name: "宠物生活",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1247",
            name: "家具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1421",
            name: "家居日用",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1453",
            name: "家庭清洁/纸品",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1495",
            name: "家用电器",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1653",
            name: "家纺",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1701",
            name: "家装建材",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1941",
            name: "手机通讯",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1972",
            name: "数码",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6033",
            name: "服饰内衣",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6153",
            name: "母婴",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6263",
            name: "汽车",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6472",
            name: "玩具乐器",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6625",
            name: "生鲜",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6706",
            name: "电脑、办公",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6831",
            name: "箱包皮具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6870",
            name: "美妆护肤",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6932",
            name: "运动户外",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7363",
            name: "钟表",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7378",
            name: "鞋靴",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7419",
            name: "食品饮料",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "128209",
            name: "旅游休闲",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "135835",
            name: "图书",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "376707",
            name: "二手",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 2,
            },
          },
          {
            catId: "377078",
            name: "生活服务",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "378136",
            name: "珠宝首饰",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 2147483647,
            },
          },
          {
            catId: "381003",
            name: "教育培训",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 2147483647,
            },
          },
          {
            catId: "429008",
            name: "其他",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
        ],
        [
          {
            catId: "1001",
            name: "个人护理",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              limit: "9",
              componentCatGroup: 3,
            },
          },
          {
            catId: "1069",
            name: "农资园艺",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1142",
            name: "厨具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1208",
            name: "宠物生活",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1247",
            name: "家具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1421",
            name: "家居日用",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1453",
            name: "家庭清洁/纸品",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1495",
            name: "家用电器",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1653",
            name: "家纺",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1701",
            name: "家装建材",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1941",
            name: "手机通讯",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "1972",
            name: "数码",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6033",
            name: "服饰内衣",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6153",
            name: "母婴",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6263",
            name: "汽车",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6472",
            name: "玩具乐器",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6625",
            name: "生鲜",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6706",
            name: "电脑、办公",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6831",
            name: "箱包皮具",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6870",
            name: "美妆护肤",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "6932",
            name: "运动户外",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7363",
            name: "钟表",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7378",
            name: "鞋靴",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "7419",
            name: "食品饮料",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "128209",
            name: "旅游休闲",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "135835",
            name: "图书",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "376707",
            name: "二手",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 2,
            },
          },
          {
            catId: "377078",
            name: "生活服务",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
          {
            catId: "378136",
            name: "珠宝首饰",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 2147483647,
            },
          },
          {
            catId: "381003",
            name: "教育培训",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentIndividualAuditInfo: {},
              componentEnterpriseAuditInfo: {},
              componentCatGroup: 2147483647,
            },
          },
          {
            catId: "429008",
            name: "其他",
            fCatId: "0",
            catType: 1,
            catInfo: {
              businessInfoList: [{ sourceType: 2, onlineStatus: 1 }],
              catLevel: 1,
              highestPriceFixing: 250000,
              maxProductNum: 2147483647,
              catGroup: 2147483647,
              individualAuditInfo: {},
              enterpriseAuditInfo: {},
              componentCatGroup: 3,
            },
          },
        ],
      ],
    };
  },
  methods: {
    click_list(index, value) {
      console.log(index, value);
      // this.choose = this.choose.splice(index,1,value);
      this.$set(this.choose, index, value);
    },
  },
};
</script>
<style lang="scss" scoped>
.breadcrumb-container {
  padding-bottom: 32px;
}
.typebox {
  background: #ffffff;
  box-shadow: 0 1px 6px 0 rgba(228, 232, 235, 0.2);
  border-radius: 8px;
  margin-top: 23px;
  // margin-bottom: 64px;
  padding: 32px;
  .search {
    width: 426px;
    height: 40px;
    background: #f7f7f7;
    border-radius: 20px;
    padding: 0 12px;
    box-sizing: border-box;
    display: flex;
    align-items: center;
    margin-bottom: 20px;
    .search_main_search {
      width: 24px;
      height: 24px;
      margin-right: 5px;
      cursor: pointer;
    }
    .search_main_input {
      flex: 1;
      border: none;
      height: 24px;
      opacity: 0.9;
      font-size: 17px;
      color: #000000;
      background: #f7f7f7;
    }
  }
  .select_cate {
    width: 100%;
    position: relative;
    background: #f7f7f7;
    border-radius: 5px;
    height: 456px;
    width: 100%;
    display: flex;
  }
}
</style>